// src/components/Footer.tsx
import { useTranslations } from "next-intl";
import { Link } from "@/i18n/navigation";
import ContactForm from "./ContactForm";

export default function Footer() {
  const f = useTranslations("footer");
  const year = new Date().getFullYear();
  const ext = "text-(--muted) hover:text-coral transition-colors duration-140";

  return (
    <footer id="contact" className="bg-paper border-t border-line py-[clamp(48px,7vw,80px)]">
      <div className="wrap grid grid-cols-2 max-[820px]:grid-cols-1 gap-[clamp(32px,6vw,80px)] items-start">
        <div className="flex flex-col gap-4">
          <Link
            href="/"
            className="font-mono font-bold text-[16px] text-ink"
            aria-label={f("ariaHome")}
            title={f("titleHome")}
          >
            LA<span className="text-saffron">.</span>
          </Link>

          <nav className="flex flex-wrap gap-5 text-sm font-medium" aria-label={f("ariaExternal")}>
            <a className={ext} href="https://github.com/aylay" rel="me noopener noreferrer" target="_blank" title={f("github")}>GitHub</a>
            <a className={ext} href="https://www.linkedin.com/in/lucasattali/" rel="me noopener noreferrer" target="_blank" title={f("linkedin")}>LinkedIn</a>
            <a className={ext} href="https://www.instagram.com/aylllay/" rel="me noopener noreferrer" target="_blank" title={f("instagram")}>Instagram</a>
            <a className={ext} href="https://beavers-agency.fr/" rel="noopener noreferrer" target="_blank" title={f("beavers")}>Beavers</a>
            <a className={ext} href="https://www.skalp.shop/" rel="noopener noreferrer" target="_blank" title={f("skalp")}>Skalp</a>
          </nav>

          <nav className="flex gap-2.5 font-mono text-xs text-faint" aria-label={f("ariaLegal")}>
            <Link href="/mentions-legales" className="hover:text-cobalt transition-colors duration-140" title={f("legal")}>{f("legal")}</Link>
            <span aria-hidden="true">·</span>
            <Link href="/confidentialite" className="hover:text-cobalt transition-colors duration-140" title={f("privacy")}>{f("privacy")}</Link>
          </nav>

          <p className="font-mono text-[11px] text-faint leading-[1.9]">
            <span className="align-[-0.1em]">©</span> {year} Lucas Attali<br />
            {f("location")}
          </p>
        </div>

        <div className="max-[820px]:order-first">
          <h2 className="font-display font-semibold text-[clamp(22px,3vw,30px)] tracking-[-0.01em] mb-2">{f("heading")}</h2>
          <p className="text-muted text-[15px] max-w-[42ch] mb-4.5">{f("intro")}</p>
          <ContactForm />
        </div>
      </div>
    </footer>
  );
}

// src/lib/components/common/Footer.svelte
<script lang="ts">
	import Facebook from "$lib/assets/svg/facebook.svelte";
	import Github from "$lib/assets/svg/github.svelte";
  import Instagram from "$lib/assets/svg/instagram.svelte";
  import Linkedin from "$lib/assets/svg/linkedin.svelte";
	import Hoverable from "../utilities/Hoverable.svelte";

  let currentDate = new Date();

</script>

<footer class="bg-seance2 max-lg:px-8 py-32">
  <div class="w-11/12 mx-auto flex flex-col gap-16">

    <div class="flex justify-center">
      <p class="text-white font-bold text-[2.2rem] border-r-amber border-t-amber border-t-2 border-r-2 py-4 px-8 leading-none">
        Aylay
      </p>
    </div>

    <p class="text-center text-lilac text-[2.2rem] italic">
      « Le détail fait la qualité et la qualité n’est pas un détail. »
    </p>

    <div class="flex justify-center items-center gap-16">
      <Hoverable let:hovering={active}>
        <a href="https://www.linkedin.com/in/lucasattali" title="Profil Linkedin Lucas Attali" target="_blank" rel="external noreferrer">
          <Linkedin newClass="h-12 transition-colors {active ? 'fill-amber' : 'fill-lilac'} w-auto" />
        </a>
      </Hoverable>

      <Hoverable let:hovering={active}>
        <a href="https://www.instagram.com/aylllay" title="Profil Instagram Lucas Attali" target="_blank" rel="external noreferrer">
          <Instagram newClass="h-12 transition-colors {active ? 'fill-amber' : 'fill-lilac'} w-auto" />
        </a>
      </Hoverable>

      <Hoverable let:hovering={active}>
        <a href="https://www.facebook.com/lucas.attali" title="Profil Facebook Lucas Attali" target="_blank" rel="external noreferrer">
          <Facebook newClass="h-10 transition-colors {active ? 'fill-amber' : 'fill-lilac'} w-auto" />
        </a>
      </Hoverable>

      <Hoverable let:hovering={active}>
        <a href="https://github.com/Aylay" title="Profil Github Lucas Attali" target="_blank" rel="external noreferrer">
          <Github newClass="h-12 transition-colors {active ? 'fill-amber' : 'fill-lilac'} w-auto" />
        </a>
      </Hoverable>
    </div>

    <p class="text-center text-lilac text-[1.4rem] leading-normal">
      © {currentDate.getFullYear()} Tous droits réservés par Lucas ATTALI<br />
      Made with <a href="https://svelte.dev/" rel="external noreferrer noopener" class="underline hover:no-underline" target="_blank">Svelte</a>, <a href="https://tailwindcss.com/" rel="external noreferrer noopener" class="underline hover:no-underline" target="_blank">Tailwind CSS</a> & <a href="https://vercel.com/" rel="external noreferrer noopener" class="underline hover:no-underline" target="_blank">Vercel</a>
    </p>
  </div>

  

</footer>
