// src/routes/a-propos/+page.svelte
<script lang="ts">
  import { m } from '$lib/paraglide/messages';
  import { getLocale, localizeHref } from '$lib/paraglide/runtime';
  import Button from '$lib/components/Button.svelte';

  const locale = getLocale();
  const ogImage = `https://lucas-attali.me/img/og-image-${locale}.png`;
  const padelAlt = locale === 'fr'
    ? 'Lucas Attali sur un terrain de padel, bonnet Skalp'
    : 'Lucas Attali on a padel court, Skalp beanie';
</script>

<svelte:head>
  <title>{m.aboutTitle()} · Lucas Attali</title>
  <meta name="description" content={m.aboutMetaDescription()} />
  <meta property="og:title" content="{m.aboutTitle()} · Lucas Attali" />
  <meta property="og:description" content={m.aboutMetaDescription()} />
  <meta property="og:image" content={ogImage} />
  <meta property="og:image:alt" content="{m.aboutTitle()} · Lucas Attali" />
  <meta name="twitter:title" content="{m.aboutTitle()} · Lucas Attali" />
  <meta name="twitter:description" content={m.aboutMetaDescription()} />
  <meta name="twitter:image" content={ogImage} />
</svelte:head>

<!-- Hero : bande cobalt, grille texte / photo padel -->
<section class="bg-cobalt text-cloud py-[clamp(48px,9vw,92px)]">
  <div class="wrap grid grid-cols-[1.05fr_0.95fr] max-[820px]:grid-cols-1 gap-[clamp(28px,5vw,60px)] items-center">
    <div class="rv">
      <span class="block font-mono text-[11px] tracking-[.02em] text-cloud/90 mb-4.5">{m.aboutEyebrow()}</span>
      <h1 class="font-display font-bold text-[clamp(42px,7.5vw,90px)] leading-[.92] tracking-tight mb-5.5">{m.aboutH1()}</h1>
      <p class="text-[clamp(16px,2.1vw,20px)] leading-[1.55] text-cloud/90 max-w-[46ch]">{m.aboutLede()}</p>
    </div>
    <figure class="ab-hero-fig relative rounded-2xl overflow-hidden bg-teal-deep aspect-square max-[820px]:max-w-85 max-[820px]:mx-auto rv">
      <enhanced:img
        src="$lib/assets/lucas-padel-skalp.webp"
        alt={padelAlt}
        sizes="(min-width: 820px) 50vw, 340px"
        loading="eager"
      />
      <figcaption class="absolute left-3.5 bottom-3 z-2 font-mono text-[11px] text-cloud/85">{m.aboutPadelCaption()}</figcaption>
    </figure>
  </div>
</section>

<!-- Bio : texte gauche, portrait droite -->
<section class="py-[clamp(52px,9vw,96px)] wrap">
  <div class="grid grid-cols-[1.4fr_0.85fr] max-[820px]:grid-cols-1 gap-[clamp(28px,5vw,60px)] items-start rv">
    <div class="[&>p]:text-[17px] [&>p]:leading-[1.72] [&>p]:mb-4.5 [&>p]:max-w-[60ch] [&>p:last-child]:mb-0">
      <p>{m.aboutP1()}</p>
      <p>{m.aboutPSkalp()}</p>
      <p>{m.aboutP2()}</p>
      <p>{m.aboutP3()}</p>
    </div>
    <figure class="ab-portrait relative border border-(--line) rounded-[14px] overflow-hidden bg-(--card) max-[820px]:max-w-85">
      <enhanced:img
        src="$lib/assets/lucas-portrait.jpg"
        alt="Lucas Attali"
        sizes="(min-width: 820px) 35vw, 340px"
        loading="lazy"
      />
      <figcaption class="font-mono text-[11px] text-(--faint) px-3.5 py-2.5">Lucas Attali</figcaption>
    </figure>
  </div>
</section>

<!-- En bref : bande sarcelle profond -->
<section class="bg-teal-deep text-cloud">
  <div class="wrap py-[clamp(48px,8vw,88px)] rv">
    <p class="font-mono text-[11px] tracking-[.12em] text-saffron mb-5.5">{m.aboutInShort()}</p>
    <dl class="facts-dl">
      <div class="border-t border-cloud/22 pt-2.5">
        <dt class="font-mono text-[11px] tracking-wider text-saffron mb-1.25">{m.factBaseL()}</dt>
        <dd class="text-[15px] text-cloud">{m.factBaseV()}</dd>
      </div>
      <div class="border-t border-cloud/22 pt-2.5">
        <dt class="font-mono text-[11px] tracking-wider text-saffron mb-1.25">{m.factLangsL()}</dt>
        <dd class="text-[15px] text-cloud">{m.factLangsV()}</dd>
      </div>
      <div class="border-t border-cloud/22 pt-2.5">
        <dt class="font-mono text-[11px] tracking-wider text-saffron mb-1.25">{m.factCourtL()}</dt>
        <dd class="text-[15px] text-cloud">{m.factCourtV()}</dd>
      </div>
      <div class="border-t border-cloud/22 pt-2.5">
        <dt class="font-mono text-[11px] tracking-wider text-saffron mb-1.25">{m.factCompanionL()}</dt>
        <dd class="text-[15px] text-cloud">{m.factCompanionV()}</dd>
      </div>
      <div class="border-t border-cloud/22 pt-2.5">
        <dt class="font-mono text-[11px] tracking-wider text-saffron mb-1.25">{m.factHeadingL()}</dt>
        <dd class="text-[15px] text-cloud">{m.factHeadingV()}</dd>
      </div>
    </dl>
    <div class="border-t border-cloud/28 pt-4 flex justify-between font-mono text-[11px] text-cloud/62">
      <span>Roquebrune · 43.5, 6.63</span>
      <span>Sydney · -33.87, 151.21</span>
    </div>
  </div>
</section>

<!-- CTAs -->
<section class="py-[clamp(52px,9vw,96px)] wrap">
  <div class="flex flex-wrap gap-3 rv">
    <Button href={localizeHref('/parcours')}>{m.ctaJourney()}</Button>
    <Button href="#contact" variant="secondary">{m.ctaContact()}</Button>
  </div>
</section>

// src/app/[locale]/a-propos/page.tsx
import { use } from "react";
import type { Metadata } from "next";
import Image from "next/image";
import { setRequestLocale, getTranslations } from "next-intl/server";
import { useTranslations, useLocale } from "next-intl";
import Button from "@/components/Button";
import { buildMetadata } from "@/lib/seo";
import padel from "@/assets/lucas-padel-skalp.webp";
import portrait from "@/assets/lucas-portrait.jpg";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: "meta" });
  return buildMetadata(locale, {
    title: t("aboutTitle"),
    description: t("aboutDescription"),
    path: "/a-propos",
    ogAlt: t("aboutTitle"),
  });
}

export default function About({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = use(params);
  setRequestLocale(locale);
  const t = useTranslations("about");
  const lang = useLocale();
  const padelAlt =
    lang === "fr"
      ? "Lucas Attali sur un terrain de padel, bonnet Skalp"
      : "Lucas Attali on a padel court, Skalp beanie";
  const tHome = useTranslations("home");

  return (
    <>
      {/* Hero : bande cobalt, grille texte / photo padel */}
      <section className="bg-cobalt text-cloud py-[clamp(48px,9vw,92px)]">
        <div className="wrap grid grid-cols-[1.05fr_0.95fr] max-[820px]:grid-cols-1 gap-[clamp(28px,5vw,60px)] items-center">
          <div className="rv">
            <span className="block font-mono text-[11px] tracking-[.02em] text-cloud/90 mb-4.5">{t("aboutEyebrow")}</span>
            <h1 className="font-display font-bold text-[clamp(42px,7.5vw,90px)] leading-[.92] tracking-tight mb-5.5">{t("aboutH1")}</h1>
            <p className="text-[clamp(16px,2.1vw,20px)] leading-[1.55] text-cloud/90 max-w-[46ch]">{t("aboutLede")}</p>
          </div>
          <figure className="ab-hero-fig relative rounded-2xl overflow-hidden bg-teal-deep aspect-square max-[820px]:max-w-85 max-[820px]:mx-auto rv">
            <Image
              src={padel}
              alt={padelAlt}
              fill
              sizes="(min-width: 820px) 50vw, 340px"
              priority
              className="object-cover mix-blend-luminosity opacity-95"
            />
            <figcaption className="absolute left-3.5 bottom-3 z-2 font-mono text-[11px] text-cloud/85">{t("aboutPadelCaption")}</figcaption>
          </figure>
        </div>
      </section>

      {/* Bio : texte gauche, portrait droite */}
      <section className="py-[clamp(52px,9vw,96px)] wrap">
        <div className="grid grid-cols-[1.4fr_0.85fr] max-[820px]:grid-cols-1 gap-[clamp(28px,5vw,60px)] items-start rv">
          <div className="[&>p]:text-[17px] [&>p]:leading-[1.72] [&>p]:mb-4.5 [&>p]:max-w-[60ch] [&>p:last-child]:mb-0">
            <p>{t("aboutP1")}</p>
            <p>{t("aboutPSkalp")}</p>
            <p>{t("aboutP2")}</p>
            <p>{t("aboutP3")}</p>
          </div>
          <figure className="ab-portrait relative border border-line rounded-[14px] overflow-hidden bg-card max-[820px]:max-w-85">
            <div className="relative aspect-4/5">
              <Image
                src={portrait}
                alt="Lucas Attali"
                fill
                sizes="(min-width: 820px) 35vw, 340px"
                className="object-cover"
              />
            </div>
            <figcaption className="font-mono text-[11px] text-faint px-3.5 py-2.5">Lucas Attali</figcaption>
          </figure>
        </div>
      </section>

      {/* En bref : bande sarcelle profond */}
      <section className="bg-teal-deep text-cloud">
        <div className="wrap py-[clamp(48px,8vw,88px)] rv">
          <p className="font-mono text-[11px] tracking-[.12em] text-saffron mb-5.5">{t("aboutInShort")}</p>
          <dl className="facts-dl">
            {([
              ["factBaseL", "factBaseV"],
              ["factLangsL", "factLangsV"],
              ["factCourtL", "factCourtV"],
              ["factCompanionL", "factCompanionV"],
              ["factHeadingL", "factHeadingV"],
            ] as const).map(([l, v]) => (
              <div key={l} className="border-t border-cloud/22 pt-2.5">
                <dt className="font-mono text-[11px] tracking-wider text-saffron mb-1.25">{t(l)}</dt>
                <dd className="text-[15px] text-cloud">{t(v)}</dd>
              </div>
            ))}
          </dl>
          <div className="border-t border-cloud/28 pt-4 flex justify-between font-mono text-[11px] text-cloud/62">
            <span>Roquebrune-sur-Argens, France · 43.5, 6.63</span>
            <span>{tHome("pinSydney")} · -33.87, 151.21</span>
          </div>
        </div>
      </section>

      {/* CTAs */}
      <section className="py-[clamp(52px,9vw,96px)] wrap">
        <div className="flex flex-wrap gap-3 rv">
          <Button href="/parcours">{tHome("ctaJourney")}</Button>
          <Button href="#contact" variant="secondary">{tHome("ctaContact")}</Button>
        </div>
      </section>
    </>
  );
}
