// src/lib/components/Button.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  let {
    href,
    variant = 'primary',
    children,
  }: {
    href: string;
    variant?: 'primary' | 'secondary-cobalt' | 'secondary';
    children: Snippet;
  } = $props();
</script>

{#if variant === 'primary'}
  <a
    class="font-sans text-[15px] font-semibold px-6 py-3.25 rounded-lg border-2 border-transparent bg-saffron text-cobalt-deep transition-transform duration-140 hover:-translate-y-0.5 inline-block"
    {href}
  >{@render children()}</a>
{:else if variant === 'secondary-cobalt'}
  <a
    class="font-sans text-[15px] font-semibold px-6 py-3.25 rounded-lg border-2 border-cloud/45 bg-transparent text-cloud transition-[transform,border-color] duration-140 hover:border-cloud hover:-translate-y-0.5 inline-block"
    {href}
  >{@render children()}</a>
{:else}
  <a
    class="font-sans text-[15px] font-semibold px-6 py-3.25 rounded-lg border-2 border-(--line-2) bg-transparent text-(--text) transition-transform duration-140 hover:-translate-y-0.5 inline-block"
    {href}
  >{@render children()}</a>
{/if}

// src/components/Button.tsx
import { Link } from "@/i18n/navigation";

type Variant = "primary" | "secondary-cobalt" | "secondary";

const styles: Record<Variant, string> = {
  primary: "border-transparent bg-saffron text-cobalt-deep transition-transform",
  "secondary-cobalt":
    "border-cloud/45 bg-transparent text-cloud transition-[transform,border-color] hover:border-cloud",
  secondary: "border-(--line-2) bg-transparent text-(--text) transition-transform",
};

export default function Button({
  href,
  variant = "primary",
  children,
}: {
  href: string;
  variant?: Variant;
  children: React.ReactNode;
}) {
  const cls = `font-sans text-[15px] font-semibold px-6 py-3.25 rounded-lg border-2 duration-140 hover:-translate-y-0.5 inline-block ${styles[variant]}`;
  return href.startsWith("/") ? (
    <Link href={href} className={cls}>{children}</Link>
  ) : (
    <a href={href} className={cls}>{children}</a>
  );
}
