// src/lib/components/FormationItem.svelte
<script lang="ts">
  let {
    title,
    subtitle,
    year,
  }: {
    title: string;
    subtitle?: string;
    year?: string;
  } = $props();
</script>

<li class="border-t border-(--line) pt-3">
  <div class="font-display font-semibold text-[18px]">{title}</div>
  {#if subtitle}<div class="text-[14px] text-(--muted)">{subtitle}</div>{/if}
  {#if year}<div class="font-mono text-[11px] text-(--faint)">{year}</div>{/if}
</li>

// src/components/FormationItem.tsx
export default function FormationItem({
  title,
  subtitle,
  year,
}: {
  title: string;
  subtitle?: string;
  year?: string;
}) {
  return (
    <li className="border-t border-line pt-3">
      <div className="font-display font-semibold text-[18px]">{title}</div>
      {subtitle && <div className="text-[14px] text-muted">{subtitle}</div>}
      {year && <div className="font-mono text-[11px] text-faint">{year}</div>}
    </li>
  );
}
