// src/components/ContactForm.tsx
"use client";

import { useActionState, useEffect, useRef } from "react";
import { useTranslations } from "next-intl";
import { sendContact, type ContactState } from "@/app/actions/contact";

const inputClass =
  "font-sans text-[15px] text-(--text) bg-(--card) border border-(--line) rounded-[9px] px-3.25 py-2.75 w-full transition-colors duration-140 focus:border-cobalt focus:outline-none";
const labelClass = "flex flex-col gap-1.5 text-[13px] font-medium text-(--muted)";

const initial: ContactState = { status: "idle" };

export default function ContactForm() {
  const t = useTranslations("form");
  const formRef = useRef<HTMLFormElement>(null);
  const [state, formAction, isPending] = useActionState(sendContact, initial);

  // Vide le formulaire après un envoi réussi
  useEffect(() => {
    if (state.status === "ok") formRef.current?.reset();
  }, [state]);

  return (
    <form ref={formRef} action={formAction} className="flex flex-col gap-3.5" noValidate>
      <div className="grid grid-cols-2 max-[480px]:grid-cols-1 gap-3.5">
        <label className={labelClass} htmlFor="cf-firstName">
          <span>{t("firstName")}</span>
          <input id="cf-firstName" className={inputClass} name="firstName" autoComplete="given-name" required />
        </label>
        <label className={labelClass} htmlFor="cf-lastName">
          <span>{t("lastName")}</span>
          <input id="cf-lastName" className={inputClass} name="lastName" autoComplete="family-name" required />
        </label>
      </div>
      <label className={labelClass} htmlFor="cf-email">
        <span>{t("email")}</span>
        <input id="cf-email" className={inputClass} type="email" name="email" autoComplete="email" required />
      </label>
      <label className={labelClass} htmlFor="cf-subject">
        <span>{t("subject")}</span>
        <input id="cf-subject" className={inputClass} name="subject" required />
      </label>
      <label className={labelClass} htmlFor="cf-message">
        <span>{t("message")}</span>
        <textarea id="cf-message" className={`${inputClass} resize-y min-h-24`} name="message" rows={4} required />
      </label>

      {/* Bot trap : champ caché qui doit rester vide */}
      <div className="absolute left-[-9999px] w-px h-px overflow-hidden" aria-hidden="true">
        <label>
          Company
          <input name="company" tabIndex={-1} autoComplete="off" />
        </label>
      </div>

      <div className="flex flex-wrap items-center gap-4 mt-1">
        <button
          type="submit"
          disabled={isPending}
          className="font-sans text-[15px] font-semibold px-6 py-3.25 rounded-lg cursor-pointer border-2 border-transparent bg-saffron text-cobalt-deep transition-transform duration-140 hover:-translate-y-0.5 disabled:opacity-60 disabled:cursor-default"
        >
          {isPending ? t("sending") : t("send")}
        </button>
        <p
          className={`text-[13px] font-mono ${
            state.status === "ok" ? "text-teal" : state.status === "error" ? "text-coral" : ""
          }`}
          role="status"
          aria-live="polite"
        >
          {state.status === "ok" ? t("success") : state.status === "error" ? t("error") : ""}
        </p>
      </div>
    </form>
  );
}

// src/lib/components/ContactForm.svelte
<script lang="ts">
  import { m } from '$lib/paraglide/messages';

  let firstName = $state('');
  let lastName = $state('');
  let email = $state('');
  let subject = $state('');
  let message = $state('');
  let company = $state(''); // honeypot — must stay empty
  let status = $state<'idle' | 'sending' | 'ok' | 'error'>('idle');

  async function submit(e: SubmitEvent) {
    e.preventDefault();
    if (status === 'sending') return;
    if (!firstName || !lastName || !email || !subject || !message) {
      status = 'error';
      return;
    }
    status = 'sending';
    try {
      const res = await fetch('/api/contact', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ firstName, lastName, email, subject, message, company })
      });
      const data = await res.json().catch(() => ({ ok: false }));
      if (res.ok && data.ok) {
        status = 'ok';
        firstName = lastName = email = subject = message = '';
      } else {
        status = 'error';
      }
    } catch {
      status = 'error';
    }
  }

  const inputClass = 'font-sans text-[15px] text-(--text) bg-(--card) border border-(--line) rounded-[9px] px-3.25 py-2.75 w-full transition-colors duration-140 focus:border-cobalt focus:outline-none';
  const labelClass = 'flex flex-col gap-1.5 text-[13px] font-medium text-(--muted)';
</script>

<form class="flex flex-col gap-3.5" onsubmit={submit} novalidate>
  <div class="grid grid-cols-2 max-[480px]:grid-cols-1 gap-3.5">
    <label class={labelClass} for="cf-firstName">
      <span>{m.formFirstName()}</span>
      <input id="cf-firstName" class={inputClass} bind:value={firstName} name="firstName" autocomplete="given-name" required />
    </label>
    <label class={labelClass} for="cf-lastName">
      <span>{m.formLastName()}</span>
      <input id="cf-lastName" class={inputClass} bind:value={lastName} name="lastName" autocomplete="family-name" required />
    </label>
  </div>
  <label class={labelClass} for="cf-email">
    <span>{m.formEmail()}</span>
    <input id="cf-email" class={inputClass} type="email" bind:value={email} name="email" autocomplete="email" required />
  </label>
  <label class={labelClass} for="cf-subject">
    <span>{m.formSubject()}</span>
    <input id="cf-subject" class={inputClass} bind:value={subject} name="subject" required />
  </label>
  <label class={labelClass} for="cf-message">
    <span>{m.formMessage()}</span>
    <textarea id="cf-message" class="{inputClass} resize-y min-h-24" bind:value={message} name="message" rows="4" required></textarea>
  </label>

  <!-- Bot trap: hidden field that must stay empty -->
  <div class="absolute left-[-9999px] w-px h-px overflow-hidden" aria-hidden="true">
    <label>Company<input bind:value={company} name="company" tabindex="-1" autocomplete="off" /></label>
  </div>

  <div class="flex flex-wrap items-center gap-4 mt-1">
    <button
      type="submit"
      class="font-sans text-[15px] font-semibold px-6 py-3.25 rounded-lg cursor-pointer border-2 border-transparent bg-saffron text-cobalt-deep transition-transform duration-140 hover:-translate-y-0.5 disabled:opacity-60 disabled:cursor-default"
      disabled={status === 'sending'}
    >
      {status === 'sending' ? m.formSending() : m.formSend()}
    </button>
    <p
      class="text-[13px] font-mono {status === 'ok' ? 'text-teal' : status === 'error' ? 'text-coral' : ''}"
      role="status"
      aria-live="polite"
    >
      {#if status === 'ok'}{m.formSuccess()}{:else if status === 'error'}{m.formError()}{/if}
    </p>
  </div>
</form>
